# Generated by Django 4.2 on 2023-06-17 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vhmsapp', '0003_remove_animal_animalname_animal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Animal Name '),
        ),
    ]
