# Generated by Django 4.2 on 2023-06-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vhmsapp', '0004_person_user_alter_animal_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
    ]
