# Generated by Django 3.1.2 on 2023-06-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhmsapp', '0008_auto_20230626_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images/'),
        ),
    ]
