# Generated by Django 4.2 on 2023-06-27 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vhmsapp', '0011_animal_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='doctor',
        ),
    ]
